### ISSUE TITLE
How can multiple users signup and have their environments

### ISSUE THREAD

**Issue by mardillu** [DeveloperOnCall/crudbooster#4]
Hi, I am just trying out this adaptation of crudbooster. I have set everything up and I am wondering how multi-tenancy is supported. I mean how can users signup and have their own environment which is separate from other users' both in terms of views and data since I suppose this is the main reason for multi-tenancy.
I also get this error when I run the app **Database [tenant] not configured.** How do I configure this
Thanks

**Comment by DeveloperOnCall** [comment]
@SEzekiel Sorry for delay in response I didn't see the notice there was an issue added.

There are a few things you need to set up to enable the multi-tenant. Did you take a look at this:
https://github.com/crocodic-studio/crudbooster/issues/813#issuecomment-452952170

Also (before you add my version of CRUDBooster) make sure to do the set up mentioned here:
https://github.com/hyn/multi-tenant#installation

I am almost always on Slack if you need a hand.
D.
